#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.orig/ 0
cp -r ../snappyHexMesh/constant/polyMesh constant
runApplication mapFields ../simpleFoam -sourceTime latestTime -consistent
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

#------------------------------------------------------------------------------
